# Generated by Django 3.2.4 on 2022-05-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(default='', max_length=100, verbose_name='地点')),
                ('type', models.CharField(default='', max_length=100, verbose_name='类别')),
                ('name', models.CharField(default='', max_length=100, verbose_name='名称')),
                ('content', models.CharField(default='', max_length=200, verbose_name='其他内容')),
                ('rq', models.DateField(null=True, verbose_name='日期')),
            ],
            options={
                'db_table': 'acdata',
            },
        ),
        migrations.CreateModel(
            name='AcdataMd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdpath', models.CharField(default='', max_length=200, verbose_name='图片路径')),
            ],
            options={
                'db_table': 'acdataMd',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, verbose_name='用户名')),
                ('pwd', models.CharField(default='', max_length=100, verbose_name='密码')),
                ('flag', models.CharField(default='', max_length=10, verbose_name='标记')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Concerns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'concerns',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bm', models.CharField(default='', max_length=100, verbose_name='病虫药害编码')),
                ('name', models.CharField(default='', max_length=100, verbose_name='病虫药害名称')),
                ('info', models.TextField(default='', verbose_name='简介')),
                ('sgt', models.TextField(default='', verbose_name='防治建议')),
                ('type', models.CharField(default='', max_length=100, verbose_name='类别')),
                ('num', models.IntegerField(default=0, verbose_name='搜索次数')),
            ],
            options={
                'db_table': 'guide',
            },
        ),
        migrations.CreateModel(
            name='GuideMd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdpath', models.CharField(default='', max_length=200, verbose_name='图片路径')),
            ],
            options={
                'db_table': 'guideMd',
            },
        ),
        migrations.CreateModel(
            name='Myfav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'myfav',
            },
        ),
        migrations.CreateModel(
            name='QAIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1', models.CharField(default='', max_length=100, verbose_name='结果1')),
                ('rd1', models.CharField(default='', max_length=100, verbose_name='结果1相似度')),
                ('r2', models.CharField(default='', max_length=100, verbose_name='结果2')),
                ('rd2', models.CharField(default='', max_length=100, verbose_name='结果2相似度')),
                ('r3', models.CharField(default='', max_length=100, verbose_name='结果3')),
                ('rd3', models.CharField(default='', max_length=100, verbose_name='结果3相似度')),
            ],
            options={
                'db_table': 'qair',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qname', models.CharField(default='', max_length=100, verbose_name='提问名称')),
                ('qcontent', models.CharField(default='', max_length=500, verbose_name='问题')),
                ('qk', models.CharField(default='', max_length=500, verbose_name='用肥用药情况')),
                ('mj', models.CharField(default='', max_length=100, verbose_name='发生面积')),
                ('weather', models.CharField(default='', max_length=100, verbose_name='天气情况')),
                ('rq', models.DateField(null=True, verbose_name='日期')),
                ('addr', models.CharField(default='', max_length=200, verbose_name='定位地址')),
                ('dznum', models.IntegerField(default=0, verbose_name='点赞数')),
                ('scnum', models.IntegerField(default=0, verbose_name='浏览数')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='QuestionMd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdpath', models.CharField(default='', max_length=200, verbose_name='图片路径')),
            ],
            options={
                'db_table': 'questionMd',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=500, verbose_name='回复内容')),
                ('sj', models.DateTimeField(null=True, verbose_name='时间')),
                ('dznum', models.IntegerField(default=0, verbose_name='点赞数')),
            ],
            options={
                'db_table': 'reply',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rq', models.DateField(null=True, verbose_name='日期')),
                ('qnd', models.IntegerField(default=0, verbose_name='签到分')),
                ('stp', models.IntegerField(default=0, verbose_name='上传图片分')),
                ('myd', models.IntegerField(default=0, verbose_name='每日一答分')),
                ('fxf', models.IntegerField(default=0, verbose_name='分享分')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, verbose_name='用户名')),
                ('head', models.CharField(default='', max_length=100, verbose_name='头像')),
                ('wxid', models.CharField(default='', max_length=100, verbose_name='微信标识码')),
                ('ttscore', models.IntegerField(default=0, verbose_name='总积分')),
                ('snscore', models.IntegerField(default=0, verbose_name='7天总积分')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
