# Generated by Django 3.2.4 on 2022-05-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_admin_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='id',
            new_name='ids',
        ),
    ]
