# Generated by Django 3.2.4 on 2022-05-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_id_admin_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='ids',
            new_name='id',
        ),
    ]
