# Generated by Django 3.2.4 on 2022-05-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_ids_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='acdata',
            name='uid',
            field=models.IntegerField(null=True, verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='acdatamd',
            name='aid',
            field=models.IntegerField(null=True, verbose_name='采集数据表id'),
        ),
        migrations.AddField(
            model_name='concerns',
            name='qid',
            field=models.IntegerField(null=True, verbose_name='问答表id'),
        ),
        migrations.AddField(
            model_name='concerns',
            name='uid',
            field=models.IntegerField(null=True, verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='guidemd',
            name='gid',
            field=models.IntegerField(null=True, verbose_name='手册表id'),
        ),
        migrations.AddField(
            model_name='myfav',
            name='qid',
            field=models.IntegerField(null=True, verbose_name='问答表id'),
        ),
        migrations.AddField(
            model_name='myfav',
            name='uid',
            field=models.IntegerField(null=True, verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='qair',
            name='qid',
            field=models.IntegerField(null=True, verbose_name='问答表id'),
        ),
        migrations.AddField(
            model_name='question',
            name='uid',
            field=models.IntegerField(null=True, verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='questionmd',
            name='qid',
            field=models.IntegerField(null=True, verbose_name='问答表id'),
        ),
        migrations.AddField(
            model_name='reply',
            name='qid',
            field=models.IntegerField(null=True, verbose_name='问答表id'),
        ),
        migrations.AddField(
            model_name='reply',
            name='rid',
            field=models.IntegerField(null=True, verbose_name='回复的id'),
        ),
        migrations.AddField(
            model_name='task',
            name='uid',
            field=models.IntegerField(null=True, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='acdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='acdatamd',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='concerns',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guide',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guidemd',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='myfav',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qair',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questionmd',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
